// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-vendors.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_vendors_default = defineTool({
  name: "list_vendors",
  title: "List vendors",
  description: "List approved wedding vendors on Nivora, optionally filtered by service type (photography or catering).",
  inputSchema: {
    service: z.enum(["photography", "catering"]).optional().describe("Filter by service type"),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ service, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("vendors").select("id, vendor_name, service_type, price_range, short_description, location, experience").eq("status", "approved").order("created_at", { ascending: false }).limit(limit);
    if (service) q = q.eq("service_type", service);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { vendors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-vendor.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_vendor_default = defineTool2({
  name: "get_vendor",
  title: "Get vendor details",
  description: "Fetch full details for a single Nivora vendor by id, including packages (photography) or menu (catering).",
  inputSchema: {
    id: z2.string().uuid().describe("Vendor id")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("vendors").select("*").eq("id", id).eq("status", "approved").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Vendor not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { vendor: data }
    };
  }
});

// src/lib/mcp/tools/search-vendors.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_vendors_default = defineTool3({
  name: "search_vendors",
  title: "Search vendors",
  description: "Search approved Nivora vendors by keyword against name, description, and location.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Keyword to search"),
    service: z3.enum(["photography", "catering"]).optional(),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, service, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const like = `%${query.replace(/[%_]/g, "")}%`;
    let q = supabase.from("vendors").select("id, vendor_name, service_type, price_range, short_description, location").eq("status", "approved").or(
      `vendor_name.ilike.${like},short_description.ilike.${like},description.ilike.${like},location.ilike.${like}`
    ).limit(limit);
    if (service) q = q.eq("service_type", service);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nivora-mcp",
  title: "Nivora Wedding Vendors",
  version: "0.1.0",
  instructions: "Tools for browsing Nivora's wedding vendor marketplace. Use `search_vendors` to find vendors by keyword, `list_vendors` to browse by service (photography or catering), and `get_vendor` to fetch a specific vendor's packages, menu, and details.",
  tools: [list_vendors_default, get_vendor_default, search_vendors_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
